# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: The project
    identifier: project
    url: '#'
    weight: 100
  - name: Presentation
    parent: project
    url: '#the-project'
    weight: 110
  - name: CExA in practice
    parent: project
    url: presentation
    weight: 120
  - name: News & events
    identifier: news
    url: news
    weight: 200
  - name: Kokkos Tea-times
    parent: news
    url: kokkos-tea-time
    weight: 210
  - name: Other news & events
    parent: news
    url: news
    weight: 220
  - name: Demonstrator apps.
    identifier: demos
    url: demos
    weight: 300
  - name: Dyablo
    parent: demos
    url: dyablo
    weight: 310
  - name: GyselaX++
    parent: demos
    url: gyselax
    weight: 320
  - name: Triclade
    parent: demos
    url: triclade
    weight: 330
  - name: Tripoli-5
    parent: demos
    url: tripoli5
    weight: 340
  - name: Trust/TrioCFD
    parent: demos
    url: triocfd
    weight: 350
  - name: Our content
    identifier: doc
    url: doc
    weight: 400
  - name: Presentations
    parent: doc
    url: content
    weight: 410
  - name: Cheat Sheet for Kokkos
    parent: doc
    url: documents
    weight: 420
  - name: The team
    identifier: team
    url: team
    weight: 500
  - name: Meet us
    parent: team
    url: team
    weight: 510
  - name: Contact us
    parent: team
    url: community
    weight: 520
  - name: Join us
    parent: team
    url: join-us
    weight: 530
